### PR TITLE
Create raster layer from file

### PR DESCRIPTION
**Pull request by wang-boyu**
Partly addresses https://github.com/projectmesa/mesa-geo/issues/91.

The support for compressed files requires more effort, so I'm thinking to implement that in the next release. That probably won't be a breaking change, i.e., from

```python
RasterLayer.from_file(raster_file, cell_cls=Cell, attr_name=None)
```

to

```python
RasterLayer.from_file(raster_file, cell_cls=Cell, attr_name=None, compression="infer")
```

### CODE REVIEW

**Comment by rht** [comment]
We should be consistently use verb for function/method name. E.g. `pd.read_csv`.

**Comment by wang-boyu** [comment]
To me `read_file` is better when it's from the package level, e.g., `pd.read_csv`, `gpd.read_file`, whereas `from_file` sounds more natural for class method constructors, e.g., `pd.DataFrame.from_dict`, `gpd.GeoDataFrame.from_file`.

But this is just my personal preference.

**Comment by wang-boyu** [comment]
Shall I rename to `RasterLayer.read_file` then?

**Comment by rht** [comment]
For the pandas naming, it is not conclusive that they use `read_*` convention because it is for package level functions. But given that `geopandas` already uses `from_file`, then we have to follow suite, according to the principle of least surprise.

**Pull request merged**
