### PR TITLE
Rename master branch to main

### PR DESCRIPTION
**Pull request by wang-boyu**
Partly addresses https://github.com/projectmesa/mesa-geo/issues/46 in preparation for https://github.com/projectmesa/mesa-geo/issues/85.

We should also change the default branch settings at GitHub and Codecov.

### CODE REVIEW

**Comment by wang-boyu** [comment]
Looks like Codecov is pointing correctly at the previous commit as base commit now.

**Comment by rht** [comment]
Only @Corvince or @jackiekazil can change the default branch, and the Codecov stuff.

**Comment by jackiekazil** [comment]
master renamed to main

**Comment by jackiekazil** [comment]
codecov updated to main

**Pull request merged**
