### PR TITLE
Update mesa-geo to sync with mesa >=2.3.0

### PR DESCRIPTION
**Pull request by tpike3**
- update to geoagent, tile_layers,raster_layers pass in mesa.Model so compatible with AgentSets
- update visualization to use solara with Jupyter_viz and leaflet_viz
- remove js visualization
- update tests

### CODE REVIEW

**Review by rht — APPROVED** [review]

**Comment by rht** [comment]
Since the code is functional anyway, rather than having this in PR limbo due to the blocker being lots of boilerplate code, I'd rather approve this and then refactor later.

**Review by jackiekazil — APPROVED** [review]
LGTM

**Comment by jackiekazil** [comment]
I am okay with this being merged after conflicts are resolved.

**Comment by tpike3** [comment]
Apologies, I need to close this an reopen to fix the history conflicts so it can be merged.

**Comment by EwoutH** [comment]
Thanks for this effort!

On a bit wider note, I am (still) a proponent of moving towards a monorepo. See:
- https://monorepo.tools/
- [Misconceptions about Monorepos: Monorepo != Monolith](https://blog.nrwl.io/misconceptions-about-monorepos-monorepo-monolith-df1250d4b03c)

**Pull request closed without merging**
