### PR TITLE
create and update rtree spatial index only when needed

### PR DESCRIPTION
**Pull request by wang-boyu**
Implements https://github.com/projectmesa/mesa-geo/issues/104

Check performance of the gis example models. Execution time is the average of 10 runs, where each run contains model initialization followed by 10 steps.

| model | time in seconds | time in seconds (this PR) |
| :---: | :---: | :---: |
| agents_networks<br>(num_agents=100) | 3.18 | 0.44 |
| agents_networks<br>(num_agents=500) | 37.28 | 1.16 |
| geo_schelling<br>(default parameters) | 0.79 | 0.62 |
| geo_schelling (points & polygons)<br>(default parameters) | 1.49 | 1.19 |
| geo_sir<br>(default parameters) | 0.13 | 0.13 |
| population<br>(default parameters) | 12.88 | 10.31 |

### CODE REVIEW

**Comment by wang-boyu** [comment]
@Corvince @rht would you like to help review this PR? Thanks : )

**Comment by Corvince** [comment]
Hi, yes, I can do that hopefully tonight or tomorrow!

**Comment by Corvince** [comment]
Sorry I got some visitors, so it will take me some more days until I have a free evening

**Comment by wang-boyu** [comment]
No worries! Enjoy your holidays.

**Review by Corvince — APPROVED** [review]

**Comment by Corvince** [comment]
Finally reviewed and merged :)

Good job

**Comment by wang-boyu** [comment]
Thanks for reviewing! Appreciate it.

**Pull request merged**
